samvera/iiif_manifest

README.md
iiif_manifest.gemspec
lib/iiif_manifest/manifest_builder/record_property_builder.rb
lib/iiif_manifest/manifest_builder/structure_builder.rb
spec/lib/iiif_manifest/manifest_factory_spec.rb

I've added an optional `manifest_metadata` method to enable the addition of metadata as per the IIIF Presentation API.
I have added some lightweight validation of the metadata received to ensure it's a) an Array of Hashes, and b) the Hashes contain 'label and 'value' keys.
Pulled in changes from #10 to make the build pass.

Add metadata into the manifest

---

.rubocop.yml
.rubocop_todo.yml
iiif_manifest.gemspec
lib/iiif_manifest.rb
lib/iiif_manifest/manifest_builder.rb
lib/iiif_manifest/manifest_builder/iiif_service.rb
lib/iiif_manifest/manifest_service_locator.rb
spec/lib/iiif_manifest/manifest_builder/resource_builder_spec.rb

Speeds up this library significantly for larger manifests and removes
the dependency on IIIF::Presentation.

Use hash-powered IIIF factories.

---

README.md
lib/iiif_manifest/manifest_builder/iiif_service.rb
lib/iiif_manifest/manifest_builder/record_property_builder.rb
lib/iiif_manifest/manifest_service_locator.rb
spec/lib/iiif_manifest/manifest_factory_spec.rb

This PR adds two new methods: `search_service` and  `autocomplete_service` to support the addition of a service block to the presentation manifest containing a search service, and autocomplete service.
The autocomplete service is (as per the IIIF Search API) added within the search service and so if an autocomplete service is supplied without a search service, it will be ignored.
I've added information the README and tried to make it clear that including these services should only happen if the application has implemented the iiif search service.
Note: I have pinned the profile version to `0` because this is what UV supports. An enhancement would be to make this configurable.
```
"service": [
{
"@context": "http://iiif.io/api/search/0/context.json",
"profile": …
```

Add search_service and autocomplete_service 

---

lib/iiif_manifest/version.rb

This release will add provisional support for the IIIF Presentation 3.0 alpha spec (https://iiif.io/api/presentation/3.0/).

Bump version to 0.5.0

---

README.md
lib/iiif_manifest/v3/display_content.rb
lib/iiif_manifest/v3/manifest_builder/body_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/body_builder_spec.rb

This PR adds the ability to add a IIIF auth service to a DisplayContent resource.  I didn't work on adding this to images since I don't have that use case and it should probably be provided by the IIIF image server (through the description service `info.json`).  I passed it as a giant hash for simplicity sake but am open to other approaches.
I'm using this branch in an Avalon PR here: 
https://github.com/avalonmediasystem/avalon/blob/0b7f6a04573c3ab561e13b14673a4de21c66d173/app/models/iiif_canvas_presenter.rb#L40
https://github.com/avalonmediasystem/avalon/blob/0b7f6a04573c3ab561e13b14673a4de21c66d173/app/models/iiif_canvas_presenter.rb#L125-L151

Optional authentication service for non-image api-backed resources.

---

lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb

If your presenter implements `#media_fragment` and returns nil when there isn't a media fragment, you can end up with a canvas with a tailing `#`.  A IIIF client that we're working with doesn't like this and it doesn't serve any purpose so this PR removes the `#` when no media fragment is present.

Don't include # if there isn't any media fragment

---

.rubocop_todo.yml
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb

Currently, should `DisplayContent` be accessible on `record` but empty for https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb#L49, `#attach_content` will break (https://github.com/samvera-labs/iiif_manifest/blob/master/lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb#L67)

Ensures that empty DisplayContent values within IIIFv3 Manifest generation are handled

---

.circleci/config.yml
iiif_manifest.gemspec

This adds the necessary configuration to use CircleCI for continuous integration testing of the gem in anticipation of promoting it to the samvera GitHub organization. 
Curren builds of this branch:
https://circleci.com/gh/samvera-labs/iiif_manifest/tree/circle_ci

Add initial configuration for CircleCI

---

iiif_manifest.gemspec

CVE-2020-8130; effects developer systems only

Loosen rake dependency

---

iiif_manifest.gemspec

CVE-2020-8130
moderate severity
Vulnerable versions: <= 12.3.2
Patched version: 12.3.3
There is an OS command injection vulnerability in Ruby Rake before 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character |.

Upgrade rake (again) to address security issue

---

lib/iiif_manifest/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/manifest_builder/content_builder.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Null values for width/height/duration are not valid in Presentation 3 manifests.  This PR adds tests for that and ensures that for Canvas objects.
Also included: 
- Delegate #key? to appease rubocop

Avoid null values in manifest for width/height/duration when not present

---

lib/iiif_manifest/v3/manifest_builder/content_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Presentation 3.0 requires all annotations to have an HTTP(S) URI, contained in an id property. This PR adds URI generation for annotations and tests to ensure that the annotation id property is populated.

Add ID property to Annotation

---

lib/iiif_manifest/v3/manifest_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/body_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_builder/structure_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

According to https://iiif.io/api/presentation/3.0/#language-of-property-values, the `@none` key should be simply `none`

remove @ from none key

---

lib/iiif_manifest/v3/manifest_builder/image_service_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/body_builder_spec.rb

According to pres 3 [specs](https://iiif.io/api/presentation/3.0/#:~:text=Implementations%20should%20be,Image%20API%20services.) and a conversation with Glen Robson, because `ImageService2` is an older specification, the `id` and `type` need to be `@id` and `@type`
- add `@` to service `id` and `type`
- adjust specs

Add @ to service id and type for backwards compatibility

---

lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

According to pres 3 [specs](https://iiif.io/api/presentation/3.0/#service), there needs to be a `type` property.  Adding this property should satisfy this validation error from https://presentation-validator.iiif.io/
- add `type` property to `SearchService#initial_attributes`

add type to SearchService and AutocompleteService #initial_attributes

---

lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Currently if conditions are not met, `#populate_rendering` returns an empty array which makes the `rendering` appear in the manifest as such.  I propose to remove `rendering` from the manifest if it is empty so it can be cleaner.
- add guard for `manifest.rendering`
- refactor `#populate_rendering`
- disable rubocop `PerceivedComplexity`
- adjust specs

Adjust rendering property

---

lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

According to pres 3 [specs](https://iiif.io/api/presentation/3.0/#metadata),
> The value of the metadata property must be an array of JSON objects...
At the moment if there are no metadata, the `metadata` field is set to `null` which will thrown an error on the [validator](https://presentation-validator.iiif.io/).
- add guard for metadata so it will not appear if `nil`

make metadata not show in the manifest if nil

---

spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Misread a test this change is going to fix and enhance that test 😅 
- change `metadata` to `manifest`

fix manifest test that was misread by me in an earlier change

---

lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

It seems the rights property was not getting set.  According to the pres 3 [specs](https://iiif.io/api/presentation/3.0/#rights), rights should be a string and not an array.
- add `rights` property to v3 manifests
- assure `rights` is a string
- disable rubocop `PerceivedComplexity`

Add rights property

---

README.md
lib/iiif_manifest.rb
lib/iiif_manifest/configuration.rb
lib/iiif_manifest/manifest_builder/record_property_builder.rb
lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
spec/iiif_manifest_spec.rb
spec/lib/iiif_manifest/configuration_spec.rb

The `description`, `label`, `rights`, and `homepage` properties were not configurable and relied on the methods supplied by the `#record_property_builder`.  This made it difficult if an application uses the `#abstract` instead of `#description` to populate the `summary` property.
The above mentioned properties are configurable and fall back to its default when there is no configuration.

Add configurability to how we extract v3 manifest properties from a record

---

lib/iiif_manifest/manifest_builder/canvas_builder.rb
lib/iiif_manifest/manifest_builder/canvas_builder_factory.rb
lib/iiif_manifest/manifest_builder/structure_builder.rb
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
lib/iiif_manifest/v3/manifest_builder/structure_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

@cjcolvar This is my attempt to remove `apply_thumbnail_to(manifest)`.  It definitely turned out more hairy than I thought.  I couldn't manage to find a way to test it either without investing a lot more time into it.  This changed a lot of files so I'm not fully convinced it worth it.  Let me know what you think, or if there's a better way 😅

remove apply thumbnail to manifest and fix specs

---

lib/iiif_manifest/manifest_builder/canvas_builder.rb
lib/iiif_manifest/manifest_builder/canvas_builder_factory.rb
lib/iiif_manifest/manifest_builder/structure_builder.rb
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
lib/iiif_manifest/v3/manifest_builder/structure_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Reverts samvera/iiif_manifest#80
to incorporate @cjcolvar's commits

Revert "remove apply thumbnail to manifest and fix specs"

---

README.md
lib/iiif_manifest.rb
lib/iiif_manifest/configuration.rb
lib/iiif_manifest/display_image.rb
lib/iiif_manifest/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/display_content.rb
lib/iiif_manifest/v3/manifest_builder.rb
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
lib/iiif_manifest/v3/manifest_builder/record_property_builder.rb
lib/iiif_manifest/v3/manifest_builder/thumbnail_builder.rb
lib/iiif_manifest/v3/manifest_service_locator.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_builder/thumbnail_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

Closes #34 
This PR will add a `thumbnail` property to each `Canvas` item and also add one to the base manifest.
- add `ThumbnailBuilder` and spec
- add to and modify existing specs
- add some configuration for the `thumbnail` property
- improve `README`
My approach was coming from using a Hyku `4.1.0` with Hyrax `3.4.1` which uses RIIIF `1.7.1` as the image server and Universal Viewer `3.1.4`.  I followed the [manifests](https://digital.lib.utk.edu/assemble/manifest/acwiley/280) from The University of Tennessee, Knoxville as an example.  I am using a scaled down version of the IIIF image itself as the thumbnail instead of a pre-generated image for now.  Also, since UV works fine with displaying thumbnails with a version 2 manifest, the focus was on version 3 to address this issue: …

Add thumbnail property

---

README.md
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

According to Presentation 3.0 spec, any resource may have `rendering` property with at least one item. This PR adds the ability to populate `rendering` property at the canvas-level.
Use-case in Avalon: Manifests in Avalon may contain more than one canvas, and each canvas contains a waveform dataset which is an alternative representation of the resource in the Canvas.

Add rendering property at Canvas level

---

lib/iiif_manifest/v3/manifest_builder/choice_builder.rb
spec/lib/iiif_manifest/v3/manifest_factory_spec.rb

When adding generation of an ID value to the Annotation field we missed the case for the `Choice` construct. This PR fixes that oversight by adding ID generation to the `choice_builder.rb`

Add id value to "Choice" annotations

---

.gitignore
lib/iiif_manifest/v3/annotation_content.rb
lib/iiif_manifest/v3/manifest_builder/annotation_content_builder.rb
lib/iiif_manifest/v3/manifest_builder/body_builder.rb
spec/lib/iiif_manifest/v3/manifest_builder/body_builder_spec.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb

Presentation 3 Annotation bodies do not require an id field unless they are linking to content that must be downloaded, such as a transcript file. Additionally, there may be use cases where a user needs or wants to provide their own ID to the annotations themselves. Providing id attrs for annotation_content and removing the requirement for a URL allows us to provide greater granularity to accommodate these use cases.

Redesign id assignment in annotation_content

---

lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb

The #populate method in the V3 canvas builder performs a `collect` on the input. This caused a NoMethodError to be generated when the input was nil. Changing the guard clause to check for `respond_to?` and `present?` should fix this case.
This commit also changes the `if` check in #display_content to a guard clause to match the style in #annotation_content.

Update guard clause to avoid NoMethodError

---

lib/iiif_manifest/v3/manifest_builder/structure_builder.rb

Copy `#path` method from CanvasBuilder to avoid doing a lot of extra work and potential fetching of data.
`CanvasBuilder#initialize` does most of the work of setting up the canvas instead of in `#apply` so it is fairly expensive especially when doing this for hundreds of canvases.

Avoid creating canvas builders just to compute id

---

lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb

Memoizing avoid duplicate fetching of these values which can be expensive especially with a large number of canvases.  In particular these are called multiple times in `#initialize` in `apply_record_properties` and then again in  `attach_*` and their guard clauses.

Memoize to avoid duplicate fetching/building of content

---

lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb

This PR allows adding a `summary` attribute to canvas elements by defining a `description` method on the canvas presenter.  This follows the pattern already implemented for setting `summary` at the manifest level.

Allow setting summary on a canvas

---

README.md
lib/iiif_manifest/v3/manifest_builder/canvas_builder.rb
lib/iiif_manifest/v3/manifest_builder/iiif_service.rb
spec/lib/iiif_manifest/v3/manifest_builder/canvas_builder_spec.rb

Avalon is looking at implementing IIIF content search 2.0 API to facilitate searching within A/V transcripts. Our expected implementation will have a search service within each leaf node (canvas) as mentioned in avalonmediasystem/avalon#5795. To that end, we need to add an arbitrary service declaration at the canvas level. 
Future improvement could be to expand the `SearchService` and `AutocompleteService` classes to handle both Content Search 1.0 and 2.0, and provide those at the canvas level to match the behavior at the manifest level. For the purposes of this initial work, however, it should be sufficient to just have an arbitrary service handler.

Allow arbitrary service resources at the Canvas level

---

.circleci/config.yml

Remove Ruby 2.5 and 2.6 from CI
